export type SizeScalingMode = 'linear' | 'sqrt' | 'log';

export type ArbConfig = {
  enabled: boolean;
  scanIntervalMs: number;
  minEdgeBps: number;
  minProfitUsd: number;
  minLiquidityUsd: number;
  maxSpreadBps: number;
  maxHoldMinutes: number;
  tradeBaseUsd: number;
  maxPositionUsd: number;
  maxWalletExposureUsd: number;
  sizeScaling: SizeScalingMode;
  slippageBps: number;
  feeBps: number;
  startupCooldownSeconds: number;
  marketCooldownSeconds: number;
  maxTradesPerHour: number;
  maxConsecutiveFailures: number;
  dryRun: boolean;
  liveTrading: string;
  minPolGas: number;
  approveUnlimited: boolean;
  stateDir: string;
  decisionsLog: string;
  killSwitchFile: string;
  snapshotState: boolean;
  maxConcurrentTrades: number;
  debugTopN: number;
  unitsAutoFix: boolean;
  logEveryMarket: boolean;
  rpcUrl: string;
  privateKey: string;
  proxyWallet?: string;
  polymarketApiKey: string;
  polymarketApiSecret: string;
  polymarketApiPassphrase: string;
  collateralTokenAddress: string;
  collateralTokenDecimals: number;
  minOrderUsd: number;
  orderSubmitMinIntervalMs: number;
  orderSubmitMaxPerHour: number;
  orderSubmitMarketCooldownSeconds: number;
  cloudflareCooldownSeconds: number;
};
