export const ARB_PRESETS = {
  off: {
    ARB_ENABLED: false,
  },
  safe_small: {
    ARB_ENABLED: true,
    ARB_SCAN_INTERVAL_MS: 2000,
    ARB_MIN_EDGE_BPS: 120,
    ARB_MIN_PROFIT_USD: 0.1,
    ARB_MIN_LIQUIDITY_USD: 2000,
    ARB_MAX_SPREAD_BPS: 200,
    ARB_TRADE_BASE_USD: 2,
    ARB_SIZE_SCALING: "sqrt",
    ARB_SLIPPAGE_BPS: 60,
    ARB_FEE_BPS: 10,
    ARB_MAX_POSITION_USD: 10,
    ARB_MAX_WALLET_EXPOSURE_USD: 25,
    ARB_MAX_TRADES_PER_HOUR: 4,
    ARB_MARKET_COOLDOWN_SECONDS: 900,
    ARB_MAX_CONSECUTIVE_FAILURES: 2,
    ARB_MAX_CONCURRENT_TRADES: 1,
    ARB_STARTUP_COOLDOWN_SECONDS: 60,
  },
  classic: {
    ARB_ENABLED: true,
    ARB_SCAN_INTERVAL_MS: 2000,
    ARB_MIN_EDGE_BPS: 120,
    ARB_MIN_PROFIT_USD: 0.1,
    ARB_MIN_LIQUIDITY_USD: 2000,
    ARB_MAX_SPREAD_BPS: 200,
    ARB_TRADE_BASE_USD: 5,
    ARB_SIZE_SCALING: "sqrt",
    ARB_SLIPPAGE_BPS: 60,
    ARB_FEE_BPS: 10,
    ARB_MAX_POSITION_USD: 25,
    ARB_MAX_WALLET_EXPOSURE_USD: 100,
    ARB_MAX_TRADES_PER_HOUR: 8,
    ARB_MARKET_COOLDOWN_SECONDS: 600,
    ARB_MAX_CONSECUTIVE_FAILURES: 2,
    ARB_MAX_CONCURRENT_TRADES: 1,
    ARB_STARTUP_COOLDOWN_SECONDS: 60,
  },
  micro: {
    ARB_ENABLED: true,
    ARB_SCAN_INTERVAL_MS: 1500,
    ARB_MIN_EDGE_BPS: 60,
    ARB_MIN_PROFIT_USD: 0.05,
    ARB_MIN_LIQUIDITY_USD: 5000,
    ARB_MAX_SPREAD_BPS: 120,
    ARB_TRADE_BASE_USD: 3,
    ARB_SIZE_SCALING: "sqrt",
    ARB_SLIPPAGE_BPS: 40,
    ARB_FEE_BPS: 10,
    ARB_MAX_POSITION_USD: 25,
    ARB_MAX_WALLET_EXPOSURE_USD: 125,
    ARB_MAX_TRADES_PER_HOUR: 15,
    ARB_MARKET_COOLDOWN_SECONDS: 300,
    ARB_MAX_CONSECUTIVE_FAILURES: 2,
    ARB_MAX_CONCURRENT_TRADES: 1,
    ARB_STARTUP_COOLDOWN_SECONDS: 60,
  },
  quality: {
    ARB_ENABLED: true,
    ARB_SCAN_INTERVAL_MS: 2500,
    ARB_MIN_EDGE_BPS: 150,
    ARB_MIN_PROFIT_USD: 0.25,
    ARB_MIN_LIQUIDITY_USD: 15000,
    ARB_MAX_SPREAD_BPS: 100,
    ARB_TRADE_BASE_USD: 8,
    ARB_SIZE_SCALING: "sqrt",
    ARB_SLIPPAGE_BPS: 30,
    ARB_FEE_BPS: 10,
    ARB_MAX_POSITION_USD: 40,
    ARB_MAX_WALLET_EXPOSURE_USD: 200,
    ARB_MAX_TRADES_PER_HOUR: 6,
    ARB_MARKET_COOLDOWN_SECONDS: 900,
    ARB_MAX_CONSECUTIVE_FAILURES: 2,
    ARB_MAX_CONCURRENT_TRADES: 1,
    ARB_STARTUP_COOLDOWN_SECONDS: 60,
  },
  late: {
    ARB_ENABLED: true,
    ARB_SCAN_INTERVAL_MS: 1000,
    ARB_MIN_EDGE_BPS: 80,
    ARB_MIN_PROFIT_USD: 0.1,
    ARB_MIN_LIQUIDITY_USD: 3000,
    ARB_MAX_SPREAD_BPS: 250,
    ARB_TRADE_BASE_USD: 5,
    ARB_SIZE_SCALING: "sqrt",
    ARB_SLIPPAGE_BPS: 80,
    ARB_FEE_BPS: 10,
    ARB_MAX_HOLD_MINUTES: 30,
    ARB_MAX_POSITION_USD: 25,
    ARB_MAX_WALLET_EXPOSURE_USD: 120,
    ARB_MAX_TRADES_PER_HOUR: 10,
    ARB_MARKET_COOLDOWN_SECONDS: 240,
    ARB_MAX_CONSECUTIVE_FAILURES: 2,
    ARB_MAX_CONCURRENT_TRADES: 1,
    ARB_STARTUP_COOLDOWN_SECONDS: 60,
  },
} as const;

export const MONITOR_PRESETS = {
  off: {
    MONITOR_ENABLED: false,
    MONITOR_REQUIRE_CONFIRMED: true,
  },
  conservative: {
    MONITOR_ENABLED: true,
    FETCH_INTERVAL: 2,
    MIN_TRADE_SIZE_USD: 250,
    TRADE_MULTIPLIER: 0.2,
    RETRY_LIMIT: 1,
    TRADE_AGGREGATION_ENABLED: true,
    TRADE_AGGREGATION_WINDOW_SECONDS: 15,
    FRONTRUN_SIZE_MULTIPLIER: 0.1,
    FRONTRUN_MAX_SIZE_USD: 25,
    GAS_PRICE_MULTIPLIER: 1.08,
    MONITOR_REQUIRE_CONFIRMED: true,
  },
  balanced: {
    MONITOR_ENABLED: true,
    FETCH_INTERVAL: 2,
    MIN_TRADE_SIZE_USD: 75,
    TRADE_MULTIPLIER: 0.2,
    RETRY_LIMIT: 1,
    TRADE_AGGREGATION_ENABLED: true,
    TRADE_AGGREGATION_WINDOW_SECONDS: 15,
    FRONTRUN_SIZE_MULTIPLIER: 0.1,
    FRONTRUN_MAX_SIZE_USD: 50,
    GAS_PRICE_MULTIPLIER: 1.08,
    MONITOR_REQUIRE_CONFIRMED: true,
  },
  active: {
    MONITOR_ENABLED: true,
    FETCH_INTERVAL: 1,
    MIN_TRADE_SIZE_USD: 25,
    TRADE_MULTIPLIER: 0.15,
    RETRY_LIMIT: 1,
    TRADE_AGGREGATION_ENABLED: true,
    TRADE_AGGREGATION_WINDOW_SECONDS: 10,
    FRONTRUN_SIZE_MULTIPLIER: 0.05,
    FRONTRUN_MAX_SIZE_USD: 100,
    GAS_PRICE_MULTIPLIER: 1.05,
    MONITOR_REQUIRE_CONFIRMED: false,
  },
  test: {
    MONITOR_ENABLED: true,
    FETCH_INTERVAL: 2,
    MIN_TRADE_SIZE_USD: 5,
    TRADE_MULTIPLIER: 0.05,
    RETRY_LIMIT: 0,
    TRADE_AGGREGATION_ENABLED: false,
    FRONTRUN_SIZE_MULTIPLIER: 0.02,
    FRONTRUN_MAX_SIZE_USD: 10,
    GAS_PRICE_MULTIPLIER: 1.02,
    MONITOR_REQUIRE_CONFIRMED: false,
  },
} as const;

export const STRATEGY_PRESETS = {
  off: {
    STRATEGY_ENABLED: false,
    ARB_ENABLED: false,
    MONITOR_ENABLED: false,
    QUICK_FLIP_ENABLED: false,
    QUICK_FLIP_TARGET_PCT: 5,
    QUICK_FLIP_STOP_LOSS_PCT: 3,
    QUICK_FLIP_MIN_HOLD_SECONDS: 30,
    AUTO_SELL_ENABLED: false,
    AUTO_SELL_THRESHOLD: 0.99,
    AUTO_SELL_MIN_HOLD_SECONDS: 120,
    ENDGAME_SWEEP_ENABLED: false,
    ENDGAME_MIN_PRICE: 0.98,
    ENDGAME_MAX_PRICE: 0.995,
    MAX_POSITION_USD: 25,
  },
  conservative: {
    STRATEGY_ENABLED: true,
    // Combines ARB + MONITOR settings
    ARB_ENABLED: true,
    MONITOR_ENABLED: true,
    // Quick Flip settings
    QUICK_FLIP_ENABLED: true,
    QUICK_FLIP_TARGET_PCT: 7, // Higher target, fewer trades
    QUICK_FLIP_STOP_LOSS_PCT: 2,
    QUICK_FLIP_MIN_HOLD_SECONDS: 60,
    // Auto-sell settings
    AUTO_SELL_ENABLED: true,
    AUTO_SELL_THRESHOLD: 0.997, // 99.7¢ (only if price improves above endgame purchases)
    AUTO_SELL_MIN_HOLD_SECONDS: 300, // Hold at least 5 minutes before auto-selling
    // Endgame sweep settings
    ENDGAME_SWEEP_ENABLED: true,
    ENDGAME_MIN_PRICE: 0.985, // 98.5¢
    ENDGAME_MAX_PRICE: 0.995, // 99.5¢ (auto-sell threshold is higher to avoid conflict)
    MAX_POSITION_USD: 15, // Conservative position sizing
    // Rate limits
    ORDER_SUBMIT_MAX_PER_HOUR: 30,
    ORDER_SUBMIT_MIN_INTERVAL_MS: 10000,
    // Existing ARB settings (from safe_small)
    ARB_SCAN_INTERVAL_MS: 2000,
    ARB_MIN_EDGE_BPS: 120,
    ARB_MAX_SPREAD_BPS: 300,
    ARB_TRADE_BASE_USD: 3,
    ARB_MAX_POSITION_USD: 15,
    ARB_MAX_WALLET_EXPOSURE_USD: 50,
    // Existing Monitor settings (from balanced)
    FETCH_INTERVAL: 2,
    MIN_TRADE_SIZE_USD: 50,
    TRADE_MULTIPLIER: 0.15,
    MONITOR_REQUIRE_CONFIRMED: true,
  },
  balanced: {
    STRATEGY_ENABLED: true,
    // Combines ARB + MONITOR settings
    ARB_ENABLED: true,
    MONITOR_ENABLED: true,
    // Quick Flip settings
    QUICK_FLIP_ENABLED: true,
    QUICK_FLIP_TARGET_PCT: 5, // 5% gain target
    QUICK_FLIP_STOP_LOSS_PCT: 3, // 3% stop loss
    QUICK_FLIP_MIN_HOLD_SECONDS: 30,
    // Auto-sell settings
    AUTO_SELL_ENABLED: true,
    AUTO_SELL_THRESHOLD: 0.996, // 99.6¢ (above endgame max to avoid conflict)
    AUTO_SELL_MIN_HOLD_SECONDS: 120, // Hold at least 2 minutes before auto-selling
    // Endgame sweep settings
    ENDGAME_SWEEP_ENABLED: true,
    ENDGAME_MIN_PRICE: 0.985, // 98.5¢ (ensures 1.3% net profit minimum after 0.2% fees)
    ENDGAME_MAX_PRICE: 0.995, // 99.5¢ (auto-sell threshold is higher)
    MAX_POSITION_USD: 25, // Balanced position sizing
    // Rate limits (higher for more trades)
    ORDER_SUBMIT_MAX_PER_HOUR: 60,
    ORDER_SUBMIT_MIN_INTERVAL_MS: 5000,
    ORDER_SUBMIT_MARKET_COOLDOWN_SECONDS: 60,
    // Existing ARB settings (from micro, optimized)
    ARB_SCAN_INTERVAL_MS: 1500,
    ARB_MIN_EDGE_BPS: 50,
    ARB_MIN_PROFIT_USD: 0.05,
    ARB_MIN_LIQUIDITY_USD: 3000,
    ARB_MAX_SPREAD_BPS: 10000, // Very permissive
    ARB_TRADE_BASE_USD: 5,
    ARB_SIZE_SCALING: "sqrt",
    ARB_SLIPPAGE_BPS: 50,
    ARB_FEE_BPS: 10,
    ARB_MAX_POSITION_USD: 25,
    ARB_MAX_WALLET_EXPOSURE_USD: 150,
    ARB_MAX_TRADES_PER_HOUR: 60,
    ARB_MARKET_COOLDOWN_SECONDS: 120,
    ARB_MAX_CONSECUTIVE_FAILURES: 3,
    ARB_MAX_CONCURRENT_TRADES: 2,
    ARB_STARTUP_COOLDOWN_SECONDS: 30,
    ARB_DEBUG_TOP_N: 10,
    // Existing Monitor settings (from active, optimized)
    FETCH_INTERVAL: 1,
    MIN_TRADE_SIZE_USD: 1, // Low minimum to catch more
    MIN_ORDER_USD: 1,
    TRADE_MULTIPLIER: 0.15,
    TRADE_AGGREGATION_ENABLED: true,
    TRADE_AGGREGATION_WINDOW_SECONDS: 10,
    FRONTRUN_SIZE_MULTIPLIER: 0.05,
    FRONTRUN_MAX_SIZE_USD: 100,
    GAS_PRICE_MULTIPLIER: 1.05,
    MONITOR_REQUIRE_CONFIRMED: false,
  },
  aggressive: {
    STRATEGY_ENABLED: true,
    ARB_ENABLED: true,
    MONITOR_ENABLED: true,
    // Quick Flip settings (tighter targets for faster trades)
    QUICK_FLIP_ENABLED: true,
    QUICK_FLIP_TARGET_PCT: 3, // Lower target, more trades
    QUICK_FLIP_STOP_LOSS_PCT: 2,
    QUICK_FLIP_MIN_HOLD_SECONDS: 15,
    // Auto-sell settings (sell higher for more profit)
    AUTO_SELL_ENABLED: true,
    AUTO_SELL_THRESHOLD: 0.95, // 95¢ - sell when positions appreciate significantly
    AUTO_SELL_MIN_HOLD_SECONDS: 60, // Hold at least 1 minute
    // Endgame sweep settings (AGGRESSIVE: buy 85-95¢ range for higher profit potential)
    ENDGAME_SWEEP_ENABLED: true,
    ENDGAME_MIN_PRICE: 0.85, // 85¢ - more uncertainty, higher potential profit (10-15% gains)
    ENDGAME_MAX_PRICE: 0.95, // 95¢ - room to appreciate before auto-sell triggers
    MAX_POSITION_USD: 50, // Aggressive position sizing
    // Rate limits (maximum)
    ORDER_SUBMIT_MAX_PER_HOUR: 120,
    ORDER_SUBMIT_MIN_INTERVAL_MS: 3000,
    ORDER_SUBMIT_MARKET_COOLDOWN_SECONDS: 30,
    // ARB settings (aggressive)
    ARB_SCAN_INTERVAL_MS: 1000,
    ARB_MIN_EDGE_BPS: 30,
    ARB_MAX_SPREAD_BPS: 15000,
    ARB_TRADE_BASE_USD: 5,
    ARB_MAX_POSITION_USD: 50,
    ARB_MAX_WALLET_EXPOSURE_USD: 250,
    ARB_MAX_TRADES_PER_HOUR: 120,
    ARB_MARKET_COOLDOWN_SECONDS: 60,
    ARB_MAX_CONCURRENT_TRADES: 3,
    ARB_STARTUP_COOLDOWN_SECONDS: 15,
    // Monitor settings (aggressive)
    FETCH_INTERVAL: 1,
    MIN_TRADE_SIZE_USD: 1,
    MIN_ORDER_USD: 1,
    FRONTRUN_MAX_SIZE_USD: 200,
    MONITOR_REQUIRE_CONFIRMED: false,
  },
} as const;

export type ArbPresetName = keyof typeof ARB_PRESETS;
export type MonitorPresetName = keyof typeof MONITOR_PRESETS;
export type StrategyPresetName = keyof typeof STRATEGY_PRESETS;

export const DEFAULT_ARB_PRESET: ArbPresetName = "safe_small";
export const DEFAULT_MONITOR_PRESET: MonitorPresetName = "balanced";
export const DEFAULT_STRATEGY_PRESET: StrategyPresetName = "off";
